[project]
name = "JH-Toolkit"
version = "1.4.1"
description = "An engineering-oriented C++20 toolkit with duck-typed concepts, header-only, RTTI-free, and concurrency-friendly."
platforms = ["Ubuntu", "macOS", "Windows"]

[project.source]
repository = "https://github.com/JeongHan-Bae/JH-Toolkit"
download = "git clone https://github.com/JeongHan-Bae/JH-Toolkit.git"

[[dependencies]]
name = "C++20 Standard Library"
platforms = ["Ubuntu", "macOS", "Windows"]
install = '''
Supports GCC 13+ and Clang 15+.
Recommended compilers: 
GCC 14.2+ (official Ubuntu builds only; PPA builds are not recommended), 14.3+, or Clang LLVM 20 (stable release).
'''
note = '''
LLVM 17/18 provided via Homebrew may not be fully stable and should be avoided in production, 
similar to the unrecommended GCC PPA builds.
GCC 13 has known issues with NTTP combined with constexpr, certain APIs are intentionally disabled via static_assert checks. 
Attempting to call these APIs on GCC13 will result in a compilation failure.
GCC 14+ has some known compile-time frontend parser issues (where correct syntax causes dangling), 
but these can be avoided by using our recommended syntax.
The MinGW series (MinGW-w64/MinGW-clang) occasionally exhibits visibility issues when mixed with Windows runtimes (msvcrt/ucrt) 
(potentially stemming from SRWLock failing to produce total order even under seq_cst fences, 
with atomic types not fully protected). Windows serves as a verification platform rather than a high-concurrency platform.
Some modules (refer to documentations) assumes POSIX semantics. The Windows implementation provides only the API, 
serving as a verification platform rather than a primary platform.

Unsupported toolchains: 
MSVC, whose behavior partially deviates from ISO expectations and whose mangling conventions are rather peculiar.

Highly recommended: 
LLVM 20. 
If no additional toolchain dependencies exist on Ubuntu, LLVM 20 can also be used as an alternative to GCC. 
On Windows, MinGW (GCC) + MSYS2 (UCRT) is recommended for minimal jitter and visibility gaps.
(Generally, it will pull GCC 14.3+ or GCC 15).
'''
version = "C++20"

[[dependencies]]
name = "Catch2"
platforms = ["Ubuntu", "macOS", "Windows"]
install = "Fetched automatically via CMake FetchContent in Debug and FastDebug builds"
version = "v3.5.0"
condition = '''
Ubuntu/macOS: CMAKE_BUILD_TYPE=Debug or FastDebug.
Windows (MinGW-UCRT): Fetched in any non-install build (including Release) to ensure stable testing without debug allocators.
'''
fetch_method = "FetchContent from GitHub"
repository = "https://github.com/catchorg/Catch2.git"
