name: Update Dependencies

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  extract-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevents using default credentials

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if required)
        run: |
          pip install -r requirements.txt || echo "No dependencies to install"

      - name: Generate dependencies.json using Python
        run: python generate_dependencies.py

      - name: Commit and push dependencies.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dependencies.json
          git commit -m "Auto-update dependencies.json" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git || echo "No changes to push"
