name: Update Dependencies

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Runs daily to keep dependencies up to date

jobs:
  extract-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate dependencies.json from CMake configuration
        run: |
          echo '{
            "project": {
              "name": "JH-Toolkit",
              "version": "1.1.2",
              "description": "A cross-platform C++20 toolkit library",
              "platforms": ["Ubuntu", "macOS", "Windows"],
              "source": {
                "repository": "https://github.com/JeongHan-Bae/JH-Toolkit",
                "download": "git clone https://github.com/JeongHan-Bae/JH-Toolkit.git"
              }
            },
            "dependencies": [
              {
                "name": "C++20 Standard Library",
                "platforms": ["Ubuntu", "macOS", "Windows"],
                "install": "Already included in modern compilers (g++-10+, clang++-10+, MSVC 19.28+)",
                "version": "C++20"
              },
              {
                "name": "Catch2",
                "platforms": ["Ubuntu", "macOS", "Windows"],
                "install": "Debug mode only, automatically fetched via CMake FetchContent",
                "version": "3.5.0",
                "condition": "CMAKE_BUILD_TYPE=Debug",
                "fetch_method": "FetchContent from GitHub"
              }
            ]
          }' > dependencies.json

      - name: Commit and push dependencies.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dependencies.json
          git commit -m "Auto-update dependencies.json" || echo "No changes to commit"
          git push || echo "No changes to push"

