name: Update Dependencies

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  extract-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevents using default credentials

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if required)
        run: |
          pip install -r requirements.txt || echo "No dependencies to install"

      - name: Generate dependencies.json using Python
        run: python .github/workflows/generate_dependencies.py

      - name: Setup SSH Signing Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SIGNING_KEY }}" > ~/.ssh/id_ed25519_signing
          chmod 600 ~/.ssh/id_ed25519_signing
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Configure Git for Signed Commits
        run: |
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/id_ed25519_signing.pub
          git config --global commit.gpgsign true
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push dependencies.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add dependencies.json
          git commit -S -m "Auto-update dependencies.json" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git || echo "No changes to push"
